# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/ELFLoader

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/ELFLoader

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/ELFLoader/CMakeFiles /data/data/com.termux/files/home/ELFLoader/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/ELFLoader/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named load

# Build rule for target.
load: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 load
.PHONY : load

# fast build rule for target.
load/fast:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/build
.PHONY : load/fast

src/loader.o: src/loader.c.o

.PHONY : src/loader.o

# target to build an object file
src/loader.c.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/loader.c.o
.PHONY : src/loader.c.o

src/loader.i: src/loader.c.i

.PHONY : src/loader.i

# target to preprocess a source file
src/loader.c.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/loader.c.i
.PHONY : src/loader.c.i

src/loader.s: src/loader.c.s

.PHONY : src/loader.s

# target to generate assembly for a file
src/loader.c.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/loader.c.s
.PHONY : src/loader.c.s

src/program_table.o: src/program_table.c.o

.PHONY : src/program_table.o

# target to build an object file
src/program_table.c.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/program_table.c.o
.PHONY : src/program_table.c.o

src/program_table.i: src/program_table.c.i

.PHONY : src/program_table.i

# target to preprocess a source file
src/program_table.c.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/program_table.c.i
.PHONY : src/program_table.c.i

src/program_table.s: src/program_table.c.s

.PHONY : src/program_table.s

# target to generate assembly for a file
src/program_table.c.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/program_table.c.s
.PHONY : src/program_table.c.s

src/section_table.o: src/section_table.c.o

.PHONY : src/section_table.o

# target to build an object file
src/section_table.c.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/section_table.c.o
.PHONY : src/section_table.c.o

src/section_table.i: src/section_table.c.i

.PHONY : src/section_table.i

# target to preprocess a source file
src/section_table.c.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/section_table.c.i
.PHONY : src/section_table.c.i

src/section_table.s: src/section_table.c.s

.PHONY : src/section_table.s

# target to generate assembly for a file
src/section_table.c.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/src/section_table.c.s
.PHONY : src/section_table.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... load"
	@echo "... src/loader.o"
	@echo "... src/loader.i"
	@echo "... src/loader.s"
	@echo "... src/program_table.o"
	@echo "... src/program_table.i"
	@echo "... src/program_table.s"
	@echo "... src/section_table.o"
	@echo "... src/section_table.i"
	@echo "... src/section_table.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

